version: '3.4'

x-db-variables: &db-variables
    POSTGRES_PASSWORD: 'password'
    POSTGRES_USER: 'bob'
    POSTGRES_DB: 'db'
services:
    dbsha256:
        build: ssl
        image: approzium_postgres_ssl
        command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
        environment:
            <<: *db-variables
            POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
            POSTGRES_HOST_AUTH_METHOD: 'scram-sha-256'
    dbmd5:
        build: ssl
        image: approzium_postgres_ssl
        command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
        environment: *db-variables
    vault:
        image: "vault:latest"
        environment:
            - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
            - VAULT_DEV_ROOT_TOKEN_ID=root
        entrypoint: vault server -dev
    authenticator:
        build: authenticator
        image: approzium_authenticator
        volumes:
            - .:/usr/src/approzium
        environment:
            - VAULT_ADDR=http://vault:8200
            - VAULT_TOKEN=root
        command: ./authenticator
    sdk:
        build: sdk
        image: approzium_sdk
        volumes:
            - .:/usr/src/approzium
            - ~/.aws/:/root/.aws/:ro
