version: '3'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=bob
            - POSTGRES_DB=db
    authenticator:
        build: authenticator
        image: authenticator
        volumes:
            - .:/usr/src/approzium
        command: ./authenticator
    sdk:
        build: sdk
        image: approzium_sdk
        volumes:
            - .:/usr/src/approzium
            - ~/.aws/:/root/.aws/:ro
