# host: 127.0.0.0
# httpport: 6000
# grpcport: 6001
# loglevel: info
# logformat: text
# lograw: false
# secretsmanager: vault
# vaultaddr: vault.example.com:8200
# vaulttoken: token
# vaulttokenpath: path/to/token
# awsregion: magrathea-1
