# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Run docker-compose build
        run: make dc-build
     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: Run Go tests
        run: make run-in-docker CMD="make run-gotests"
    
      - name: Run Python tests
        run: make run-in-docker CMD="make run-pythontests"
        
      #- name: Run E2E test
      #  run: make test
        
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: gofmt
        run: gofmt -s -w .

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python lint libraries
        run: |
          pip install isort black flake8

      - run: cd sdk/python && isort -y --recursive
      - run: cd sdk/python && black .
      - run: cd sdk/python && flake8

      # commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Required
          commit_message: Automatic lint

          # Optional branch to push to, defaults to the current branch
          # branch: feature-123

          # Optional options appended to `git-commit`
          commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # file_pattern: src/*.js tests/*.js

          # Optional local file path to the repository
          repository: .

          # Optional commit user and author settings
          commit_user_name: GitHub Actions Bot

          # Optional options appended
          # push_options: '--force'
